### PR TITLE
Feature/update/delete/leaderboard

### PR DESCRIPTION
**Pull request by ghelle2h**

### CODE REVIEW

**Review by tomthebarbarian — CHANGES_REQUESTED** [review]
Please comment out the console logs in userRoutes and think about deleteing unused commented out code in scoreboard

**Review by tomthebarbarian — COMMENTED** [review]
Looks good, thanks man

**Review by tomthebarbarian — APPROVED** [review]

**Review by tomthebarbarian — CHANGES_REQUESTED** [review]
It says you're 1 commit behind main, could you pull and rebase main again before pushing?

**Review by tomthebarbarian — APPROVED** [review]
There we go, all fixed

**Review by smartnvm — APPROVED** [review]
thanks Hamza!

**Pull request merged**
